ALTER TABLE `lutransport`.`ptodapplication` 
ADD COLUMN `seq_amt5` DOUBLE NULL DEFAULT NULL AFTER `seq_num4`,
ADD COLUMN `seq_amt6` DOUBLE NULL DEFAULT NULL AFTER `seq_amt5`,
ADD COLUMN `seq_amt7` DOUBLE NULL DEFAULT NULL AFTER `seq_amt6`,
ADD COLUMN `seq_amt8` DOUBLE NULL DEFAULT NULL AFTER `seq_amt7`,
ADD COLUMN `seq_num5` INT(11) NULL DEFAULT NULL AFTER `seq_amt8`,
ADD COLUMN `seq_num6` INT(11) NULL DEFAULT NULL AFTER `seq_num5`,
ADD COLUMN `seq_num7` INT(11) NULL DEFAULT NULL AFTER `seq_num6`,
ADD COLUMN `seq_num8` INT(11) NULL DEFAULT NULL AFTER `seq_num7`;